version: "3.9"

services:
  redis:
    image: 'bitnami/redis:latest'
    volumes:
      - db_data:/data
    command: /opt/bitnami/scripts/redis/run.sh --bind redis --save 60 1 --loglevel warning
    environment:
      - REDIS_PASSWORD=mypassword
      - REDIS_AOF_ENABLED=no 
    ports:
     - "6379:6379"
  api:
    ports:
     - "8080:8080"
    depends_on:
      - redis
    build: 
      context: /
      dockerfile: api.Dockerfile
    restart: always
  game_server:
    ports:
     - "2050:2050"
    depends_on:
      - api
    build: 
      context: /
      dockerfile: game.Dockerfile
    restart: always
volumes:
  db_data: {}

